<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261007094640 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE datei (id UUID NOT NULL, name VARCHAR(255) NOT NULL, typ VARCHAR(20) NOT NULL, vorlage BOOLEAN NOT NULL, erstellt_am TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE datei_schlagwort (datei_id UUID NOT NULL, schlagwort_id INT NOT NULL, PRIMARY KEY (datei_id, schlagwort_id))');
        $this->addSql('CREATE INDEX IDX_649CED9820D2538 ON datei_schlagwort (datei_id)');
        $this->addSql('CREATE INDEX IDX_649CED98C95E8C9A ON datei_schlagwort (schlagwort_id)');
        $this->addSql('CREATE TABLE fassung (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nummer INT NOT NULL, originalname VARCHAR(255) NOT NULL, groesse BIGINT NOT NULL, mime_typ VARCHAR(127) NOT NULL, sha256 VARCHAR(64) NOT NULL, pfad VARCHAR(500) NOT NULL, herkunft VARCHAR(20) NOT NULL, erstellt_am TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, datei_id UUID NOT NULL, quelle_video_id INT DEFAULT NULL, quelle_audio_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX fassung_sha256 ON fassung (sha256)');
        $this->addSql('CREATE UNIQUE INDEX fassung_datei_nummer ON fassung (datei_id, nummer)');
        $this->addSql('CREATE INDEX IDX_BC8F75A20D2538 ON fassung (datei_id)');
        $this->addSql('CREATE INDEX IDX_BC8F75AB4340D04 ON fassung (quelle_video_id)');
        $this->addSql('CREATE INDEX IDX_BC8F75AA7C42E8D ON fassung (quelle_audio_id)');
        $this->addSql('CREATE TABLE mappe (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, beschreibung TEXT DEFAULT NULL, vorlage BOOLEAN NOT NULL, erstellt_am TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, geaendert_am TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ergebnis_datei_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_620C50F694CC452B ON mappe (ergebnis_datei_id)');
        $this->addSql('CREATE TABLE mappe_schlagwort (mappe_id INT NOT NULL, schlagwort_id INT NOT NULL, PRIMARY KEY (mappe_id, schlagwort_id))');
        $this->addSql('CREATE INDEX IDX_C6934156405DB4F ON mappe_schlagwort (mappe_id)');
        $this->addSql('CREATE INDEX IDX_C693415C95E8C9A ON mappe_schlagwort (schlagwort_id)');
        $this->addSql('CREATE TABLE mappe_bestandteil (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position INT NOT NULL, mappe_id INT NOT NULL, datei_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX mappe_bestandteil_eindeutig ON mappe_bestandteil (mappe_id, datei_id)');
        $this->addSql('CREATE INDEX IDX_792867B26405DB4F ON mappe_bestandteil (mappe_id)');
        $this->addSql('CREATE INDEX IDX_792867B220D2538 ON mappe_bestandteil (datei_id)');
        $this->addSql('CREATE TABLE schlagwort (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C3BABBD85E237E06 ON schlagwort (name)');
        $this->addSql('ALTER TABLE datei_schlagwort ADD CONSTRAINT FK_649CED9820D2538 FOREIGN KEY (datei_id) REFERENCES datei (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE datei_schlagwort ADD CONSTRAINT FK_649CED98C95E8C9A FOREIGN KEY (schlagwort_id) REFERENCES schlagwort (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fassung ADD CONSTRAINT FK_BC8F75A20D2538 FOREIGN KEY (datei_id) REFERENCES datei (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fassung ADD CONSTRAINT FK_BC8F75AB4340D04 FOREIGN KEY (quelle_video_id) REFERENCES fassung (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fassung ADD CONSTRAINT FK_BC8F75AA7C42E8D FOREIGN KEY (quelle_audio_id) REFERENCES fassung (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mappe ADD CONSTRAINT FK_620C50F694CC452B FOREIGN KEY (ergebnis_datei_id) REFERENCES datei (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mappe_schlagwort ADD CONSTRAINT FK_C6934156405DB4F FOREIGN KEY (mappe_id) REFERENCES mappe (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE mappe_schlagwort ADD CONSTRAINT FK_C693415C95E8C9A FOREIGN KEY (schlagwort_id) REFERENCES schlagwort (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE mappe_bestandteil ADD CONSTRAINT FK_792867B26405DB4F FOREIGN KEY (mappe_id) REFERENCES mappe (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mappe_bestandteil ADD CONSTRAINT FK_792867B220D2538 FOREIGN KEY (datei_id) REFERENCES datei (id) ON DELETE RESTRICT NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE datei_schlagwort DROP CONSTRAINT FK_649CED9820D2538');
        $this->addSql('ALTER TABLE datei_schlagwort DROP CONSTRAINT FK_649CED98C95E8C9A');
        $this->addSql('ALTER TABLE fassung DROP CONSTRAINT FK_BC8F75A20D2538');
        $this->addSql('ALTER TABLE fassung DROP CONSTRAINT FK_BC8F75AB4340D04');
        $this->addSql('ALTER TABLE fassung DROP CONSTRAINT FK_BC8F75AA7C42E8D');
        $this->addSql('ALTER TABLE mappe DROP CONSTRAINT FK_620C50F694CC452B');
        $this->addSql('ALTER TABLE mappe_schlagwort DROP CONSTRAINT FK_C6934156405DB4F');
        $this->addSql('ALTER TABLE mappe_schlagwort DROP CONSTRAINT FK_C693415C95E8C9A');
        $this->addSql('ALTER TABLE mappe_bestandteil DROP CONSTRAINT FK_792867B26405DB4F');
        $this->addSql('ALTER TABLE mappe_bestandteil DROP CONSTRAINT FK_792867B220D2538');
        $this->addSql('DROP TABLE datei');
        $this->addSql('DROP TABLE datei_schlagwort');
        $this->addSql('DROP TABLE fassung');
        $this->addSql('DROP TABLE mappe');
        $this->addSql('DROP TABLE mappe_schlagwort');
        $this->addSql('DROP TABLE mappe_bestandteil');
        $this->addSql('DROP TABLE schlagwort');
    }
}
